package io.innofang.base.bean.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import io.innofang.base.bean.greendao.Bpm;

import io.innofang.base.bean.greendao.BpmDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig bpmDaoConfig;

    private final BpmDao bpmDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        bpmDaoConfig = daoConfigMap.get(BpmDao.class).clone();
        bpmDaoConfig.initIdentityScope(type);

        bpmDao = new BpmDao(bpmDaoConfig, this);

        registerDao(Bpm.class, bpmDao);
    }
    
    public void clear() {
        bpmDaoConfig.clearIdentityScope();
    }

    public BpmDao getBpmDao() {
        return bpmDao;
    }

}
